# Generated by Django 4.2.17 on 2025-01-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('playstation', 'PLAYSTATION'), ('xbox', 'XBOX'), ('nintendo', 'NINTENDO'), ('pc', 'PC')], default='pc', max_length=11),
        ),
        migrations.AddField(
            model_name='post',
            name='playstyle',
            field=models.CharField(choices=[('relaxed', 'RELAXED'), ('regular', 'REGULAR'), ('competitive', 'COMPETITIVE')], default='relaxed', max_length=11),
        ),
    ]
